name: Auto-deploy to Dokku

on:
  workflow_dispatch:
  pull_request:
#   push:
#     tags:
#       - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Dokku deploy
      uses: dokku/github-action@v1.4.0
      with:
        git_remote_url: ssh://dokku@${{ secrets.DOKKU_IP }}:22:covid19mtl.ca
        ssh_private_key: ${{ secrets.PRIVATE_KEY }}
        git_push_flags: '--force'
        trace: 1
